### ISSUE TITLE
I ran into trouble when running this open source work

### ISSUE THREAD

**Issue by RobinLiuZX** [ASCIIJK/MiN-NeurIPS2025#2]
Your work is outstanding, and I'm very interested in your open source work. When I debugged your work using pdb, I got an **"out of memory" error**. My experimental platform server GPU is also an **NVIDIA 4090 24GB**, but when I debugged and ran it on **line 131** of `MiN.py`, "self.fit_fc(train_loader, test_loader)," I got the error above. What's the cause?

I reduced the **batch_size** in the `MiN-cifar-10steps.json` file to 32 and the **buffer_size** to 4096, but the GPU memory is still insufficient. I'm desperate for help.

**Comment by RobinLiuZX** [comment]
I have solved this problem, thank you for your excellent work, after setting the above parameters, I set the environment variable with the command export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True. After enabling expandable_segments, the memory blocks can be dynamically expanded, reducing fragmentation and making free memory more easily utilized.
